# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cascade < Formula
  desc "CLI tool that applies a patch across multiple git repositories"
  homepage "https://github.com/vpukhanov/cascade"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vpukhanov/cascade/releases/download/v1.0.0/cascade_1.0.0_Darwin_x86_64.zip"
      sha256 "c8f5a876d26e4b25ccb1795495e7d2204df9051f2c174ed767ee0e391b05ac26"

      def install
        bin.install "cascade"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vpukhanov/cascade/releases/download/v1.0.0/cascade_1.0.0_Darwin_arm64.zip"
      sha256 "ed5e7cc64bd5801d1d361738133adfde329e36986c17463159274abf24094f3d"

      def install
        bin.install "cascade"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vpukhanov/cascade/releases/download/v1.0.0/cascade_1.0.0_Linux_x86_64.tar.gz"
        sha256 "e49b9b9fcb9bdb01377adf1a2574da8ff965a64428913ca22d99be7bc4b906c0"

        def install
          bin.install "cascade"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vpukhanov/cascade/releases/download/v1.0.0/cascade_1.0.0_Linux_arm64.tar.gz"
        sha256 "221858b1fc0a9052fc9d104aafbc5e3413d4892c0012f7e653f59929c58b3e2c"

        def install
          bin.install "cascade"
        end
      end
    end
  end

  test do
    system "#{bin}/cascade version"
  end
end
