# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glee < Formula
  desc "CLI tool to manage Git's local exclude patterns"
  homepage "https://github.com/vpukhanov/glee"
  version "1.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/vpukhanov/glee/releases/download/v1.2.0/glee_1.2.0_Darwin_x86_64.zip"
      sha256 "01ab183bf2248efe1d6608cb08f4b5aa289df9943155b6249b50e228267d1718"

      def install
        bin.install "glee"
      end
    end
    on_arm do
      url "https://github.com/vpukhanov/glee/releases/download/v1.2.0/glee_1.2.0_Darwin_arm64.zip"
      sha256 "4dc73d0b24845a217ad5b679b29a372327d1ea7854e64323e3b9df5dfb23debf"

      def install
        bin.install "glee"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vpukhanov/glee/releases/download/v1.2.0/glee_1.2.0_Linux_x86_64.tar.gz"
        sha256 "c92f859b9ce3d5ad270c4284066c5825aed9a2627d75b275cbfb4346f9d90a2d"

        def install
          bin.install "glee"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vpukhanov/glee/releases/download/v1.2.0/glee_1.2.0_Linux_arm64.tar.gz"
        sha256 "d619ec63bc88a548e95d16bb10cbd13d4de029f7a8029692982142b07f3576cc"

        def install
          bin.install "glee"
        end
      end
    end
  end

  test do
    system "#{bin}/glee version"
  end
end
